"use client"; // এটা লাগবে কারণ SessionProvider client-side hook

import Footer from "../component/shared/Footer";
import Navber from "../component/shared/Navber";
import "../styles/globals.css";
import { SessionProvider } from "next-auth/react";

// export const metadata = {
//   title: "Product Selling",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* NextAuth SessionProvider */}
        <SessionProvider>
          <Navber />
          <main className="min-h-[calc(100vh-300px)]">{children}</main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
